services:
  coppeliasim:
    image: murilomarinho/coppeliasim:latest
    stop_signal: SIGINT
    platform: linux/amd64 # No current build for arm64
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
      - COPPELIA_SIM_SCENE_PATH=/root/sas_tutorial_workspace/src/sas_robot_driver_coppeliasim/SampleCommunicationScene.ttt
    privileged: true # Needed for some gpu configurations.
    volumes:
      - ../../:/root/sas_tutorial_workspace/src/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    command: /bin/bash -c "
      sudo apt-get update && sudo apt-get upgrade -y
      && [ -f $$COPPELIA_SIM_SCENE_PATH ]
      && cd "$$COPPELIASIM_PATH"
      && ./coppeliaSim.sh 
      -s0 \
      $$COPPELIA_SIM_SCENE_PATH"