services:
  sas_common:
    build: .
    volumes:
      - ../../sas_robot_driver_coppeliasim:/root/sas_robot_driver_coppeliasim_devel/src/sas_robot_driver_coppeliasim
    command: /bin/bash -c "
      cd /root/sas_robot_driver_coppeliasim_devel/src/
      && ls .
      && colcon build
      && source install/setup.bash"