services:
  coppeliasim:
    image: murilomarinho/coppeliasim:latest
    stop_signal: SIGINT
    platform: linux/amd64 # No current build for arm64
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
      - COPPELIA_SIM_SCENE_FILE=SampleCommunicationScene.ttt
      - COPPELIA_SIM_CONTAINER_SCENE_PATH=/root/sas_tutorial_workspace/src
    privileged: true # Needed for some gpu configurations.
    volumes:
      - ./:/root/sas_tutorial_workspace/src/ # share current folder in host with /root/sas_tutorial_workspace/src/ in container
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    command: /bin/bash -c "
      ls "$$COPPELIA_SIM_CONTAINER_SCENE_PATH"
      && sudo apt-get update && sudo apt-get upgrade -y
      && [ -f "$$COPPELIA_SIM_CONTAINER_SCENE_PATH/$$COPPELIA_SIM_SCENE_FILE" ]
      && cd "$$COPPELIASIM_PATH"
      && ./coppeliaSim.sh 
      -s0 \
      "$$COPPELIA_SIM_CONTAINER_SCENE_PATH/$$COPPELIA_SIM_SCENE_FILE""