services:
  coppeliasim:
    build:
      dockerfile: Dockerfile_view
    platform: linux/amd64 # No current build for arm64
    stop_signal: SIGINT
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    privileged: true # Needed for some gpu configurations.
    volumes:
      - ../../:/root/sas_tutorial_workspace/src/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    command: /bin/bash -c "
      . /root/scripts/print_environment.sh
      && cd /root/sas_tutorial_workspace/src/
      && colcon build --packages-select sas_robot_driver_coppeliasim
      && source install/setup.bash
      && [ -f /root/sas_tutorial_workspace/src/sas_robot_driver_coppeliasim/SampleCommunicationScene.ttt ]
      && cd "$$COPPELIASIM_PATH"
      && ./coppeliaSim.sh #\
      -s0 \
      /root/sas_tutorial_workspace/src/sas_robot_driver_coppeliasim/SampleCommunicationScene.ttt"

  comm_test:
    build:
      dockerfile: Dockerfile_comm_test
    environment:
      - ROS_DOMAIN_ID
    tty: true
    stdin_open: true
    command: /bin/bash -c "
      . /root/scripts/print_environment.sh
      && while true; do ros2 topic list; sleep 5; done"