services:
  coppeliasim:
    build:
      dockerfile: Dockerfile_view
    platform: linux/amd64 # No current build for arm64
    stop_signal: SIGINT
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    privileged: true # Needed for some gpu configurations.
    volumes:
      - ../../:/root/sas_tutorial_workspace/src/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    # network_mode: "host" # x server related
    command: /bin/bash -c "
      echo $ROS_DOMAIN_ID
      && cd /root/sas_tutorial_workspace/src/
      && tree .
      && colcon build --packages-select sas_robot_driver_coppeliasim
      && source install/setup.bash
      && cd "$$COPPELIASIM_PATH"
      && ./coppeliaSim.sh" #\
      #&& [ -f /root/sas_tutorial_workspace/src/sas_robot_driver_coppeliasim/SampleCommunicationScene.ttt ]
      #-s0 \
      #/root/sas_tutorial_workspace/src/sas_robot_driver_coppeliasim/SampleCommunicationScene.ttt"

  comm_test:
    image: murilomarinho/sas:jazzy
    environment:
      - ROS_DOMAIN_ID
    tty: true
    stdin_open: true
    stop_signal: SIGINT
    stop_grace_period: 1m