services:
  sas_robot_driver_coppeliasim:
    build: .
    volumes:
      - ../../:/root/sas_tutorial_workspace/src/sas_robot_driver_coppeliasim/
    command: /bin/bash -c "
      cd /root/sas_tutorial_workspace/src/
      && colcon build --packages-select sas_robot_driver_coppeliasim
      && source install/setup.bash
      && ros2 run sas_robot_driver_coppeliasim simros2_example.py"