services:
  coppeliasim:
    extends:
      file: compose.yml
      service: coppeliasim

  joint_interface_example:
    image: murilomarinho/sas:jazzy
    environment:
      - ROS_DOMAIN_ID
    command: /bin/bash -c "
      sudo apt-get update && sudo apt-get upgrade -y
      && ros2 run sas_robot_driver_coppeliasim joint_interface_example.py --ros-args -p robot_topic_name:=sas_robot_driver_coppeliasim/UR5"