/bin/bash
set -e

echo "Container information..."
echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID"
cat $FASTRTPS_DEFAULT_PROFILES_FILE
echo "FASTRTPS_DEFAULT_PROFILES_FILE=$FASTRTPS_DEFAULT_PROFILES_FILE"
echo "FASTDDS_BUILTIN_TRANSPORTS=$FASTDDS_BUILTIN_TRANSPORTS"
