myrobot_1:
  ros__parameters:
    # RobotDriverCoppeliaSim (ZMQ) connection
    ip: '127.0.0.1'
    port: 23000
    timeout: 1000
    robot_joint_names: ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    # Joint limits, in degrees (converted to rad internally)
    joint_limits_min: [-360.0, -360.0, -360.0, -360.0, -360.0, -720.0]  # The last joint has no limit
    joint_limits_max: [360.0, 360.0, 360.0, 360.0, 360.0, 720.0]  # The last joint has no limit
    # RobotDriverROS control loop
    thread_sampling_time_sec: 0.002  # Robot thread is at 500 Hz
